from .calculation import *
from .date import *
from .jokes import *
from .handle_music_command import *
from .news import *
from .open_program import *
from .perform_search import *
from .time import *
from .wikipedia import *
