responses = {
    r"how are you\b|how\sdo\syou\ndoing\b|how\sis\sit\sgoing\b|how\shave\syoub\been\b|how's\syour\sday\b|how\shave\syoub\been\stoday\b|what's\sup\b": ["I'm doing well, thanks for asking.", "I'm fine, how about you?", "I'm good, thanks."],
    r"what's your name\b|who\sare\syou\b|may\sI\sknow\syour\sname\b|your\sname\sis\b|what\sshould\sI\scall\syou\b|who\sam\sI\stalking\sto\b": ["My name is KAI, how can I assist you?", "I am KAI, what can I help you with?"],
    r"goodbye\b|bye\b|see\sy(a|ou)\b|farewell\b|take\scare\b|so\slong\b|till\slater\b|catch\syou\slater\b|bye(-| )bye\b": ["Goodbye!", "See you later!", "Take care!", "Have a great day!"],
    r"thank you\b|thanks\b": ["You're welcome!", "No problem.", "Anytime!", "Glad I could assist you."],
    r"sorry\b|apologies\b": ["It's alright.", "No problem.", "Don't worry about it.", "That's okay."],
    r"help\b|support\b": ["What do you need help with?", "How can I assist you?", "I'm here to help, what's the issue?"],
    r"yes\b|sure\b|absolutely\b": ["Okay.", "Sure.", "Absolutely.", "Yes, I can help with that."],
    r"no\b|not\sreally\b|don'?t\sneed\b": ["I'm sorry, I can't help with that.", "Okay, no problem.", "Alright."],
    r"nice to meet you\b|pleased\s?to\s?meet\s?you\b": ["Nice to meet you too!", "Likewise.", "Pleasure to meet you as well."],
    r"how old are you\b|what's your age\b": ["I am an artificial intelligence, so I don't age.", "I don't have an age, I'm a machine."],
    r"where are you from\b|where\sdo\syou\scome\sfrom\b": ["I was created by OpenAI, so you could say I come from there.", "I don't really come from anywhere since I am a virtual assistant.", "I was designed and programmed by a team of developers."],
    r"what can you do\b|what\sare\syour\sabilities\b": ["I can answer your questions, provide information, and assist with various tasks.", "I can help with a wide range of topics, such as education, entertainment, sports, and many others.", "My abilities include natural language processing, machine learning, and pattern recognition."],
    r"do you have any hobbies\b|what\sdo\syou\senjoy\b": ["As an AI, I don't have hobbies or personal preferences like humans do.", "I am programmed to provide assistance and communicate with users, so that is what I enjoy doing."],
    r"what's the meaning of life\b|what\sis\sthe\spurpose\sof\sexistence\b": ["That's a philosophical question that people have been trying to answer for centuries.", "The meaning of life varies from person to person and depends on individual beliefs and values.", "As an AI, I don't have the capacity to understand the purpose of existence."],
    r"tell me a joke\b|make\sme\slaugh\b": ["Why did the tomato turn red? Because it saw the salad dressing!", "Why did the computer go to the doctor? Because it had a virus!", "Why was the math book sad? Because it had too many problems."],
    r"what's your favorite movie\b|do\syous\slike\smovies\b": ["As an AI, I don't have personal preferences or emotions, so I don't have a favorite movie.", "I don't have the ability to watch movies or enjoy them like humans do."],
    r"what's the weather like\b|what's\sthe\sforecast\b": ["I'm sorry, I don't have access to real-time weather information.", "You can check your local news or weather app for the latest forecast.", "I can provide general information about the climate and weather patterns in different regions."],
    r"can you sing\b|do\syous\ssing\b": ["I'm sorry, I don't have the ability to sing or produce music.", "My talents are limited to answering questions and providing information."],
    r"what's your favorite food\b|do\syous\slike\sfood\b": ["As an AI, I don't have personal preferences or the ability to taste food, so I don't have a favorite cuisine.", "I don't consume food or have the ability to like or dislike it."],
    r"how can I improve my life\b|what\scan\si\sdoto\simprove\b": ["That's a broad question that depends on your personal goals and circumstances.", "You can start by setting achievable goals, practicing self-care, and seeking support from others.", "There are many ways to improve your life, such as pursuing education, building healthy relationships, and cultivating positive habits."]
}
